### ISSUE TITLE
Constraint Violation

### ISSUE THREAD

**Issue by mmahler** [YubicoLabs/yubihsm-ssh-tool#1]
Followed the example instructions and received " SSH CA constraint violation ". Is there any troubleshooting advice ?

**Comment by mmahler** [comment]
Here is my output:

> user@host:~/yubihsm-ssh-tool$ openssl rsa -pubout -in ca.pem -out ca_pub.pem
> writing RSA key
> user@host:~/yubihsm-ssh-tool$ ssh-keygen -i -f ca_pub.pem -m PKCS8 >ca.pub
> user@host:~/yubihsm-ssh-tool$ yubihsm-shell -a put-asymmetric-key --authkey=0x0002 --password=`gpg -d masterkey.gpg` -i 10 -l "SSH_CA_Key" -c "sign-ssh-certificate" --in ca.pem
> Using default connector URL: http://127.0.0.1:12345
> Session keepalive set up to run every 15 seconds
> Created session 0
> Stored Asymmetric key 0x000a
> user@host:~/yubihsm-ssh-tool$ openssl genrsa -out timestamp.pem
> Generating RSA private key, 2048 bit long modulus
> .......................................................+++
> ................+++
> e is 65537 (0x10001)
> user@host:~/yubihsm-ssh-tool$ openssl rsa -pubout -in timestamp.pem -out timestamp_pub.pem
> writing RSA key
> user@host:~/yubihsm-ssh-tool$ pipenv run yubihsm-ssh-tool templ -T timestamp_pub.pem -k 10 -b 36000 -a 36000 -p root
> user@host:~/yubihsm-ssh-tool$ yubihsm-shell -a put-template --authkey=0x0002 -p `gpg -d masterkey.gpg` -i 20 -l "SSH_Template" -A template-ssh --in tem
> pl.dat
> Using default connector URL: http://127.0.0.1:12345
> Session keepalive set up to run every 15 seconds
> Created session 0
> Stored Template object 0x0014
> user@host:~/yubihsm-ssh-tool$ ssh-keygen -t rsa -N "" -f ./id_rsa
> Generating public/private rsa key pair.
> Your identification has been saved in ./id_rsa.
> Your public key has been saved in ./id_rsa.pub.
> The key fingerprint is:
> SHA256:V3PhQFhWh212T/5aJ0j4Br3SHrSnKxTbWn0j16giD/I user@host
> The key's randomart image is:
> +---[RSA 2048]----+
> |           +=.oo.|
> |          .. o.o*|
> |           oo o=o|
> |          +.+o  o|
> |        S .X = .o|
> |         .+ @.=o*|
> |      . .. * =o=o|
> |       o..+ + .  |
> |        Eo.o..   |
> +----[SHA256]-----+
> user@host:~/yubihsm-ssh-tool$ pipenv run yubihsm-ssh-tool req -s ca_pub.pem -t timestamp.pem -I user-identity -n username -V -5h:+5h id_rsa.pub
> Hash is: b'675d701b2848fc9a1964ee309afc547fe68c5d196cd5e2458268f5f65758cc4e'
> user@host:~/yubihsm-ssh-tool$ yubihsm-shell -a sign-ssh-certificate --authkey=0x0002 --password=`gpg -d masterkey.gpg` -i 10 --template-id 20 -A rsa-pkcs1-sha256 --in req.dat --out id_rsa-cert.pub
> Using default connector URL: http://127.0.0.1:12345
> Session keepalive set up to run every 15 seconds
> Created session 0
> Failed to get certificate signature: SSH CA constraint violation
> Unable to get ssh certificate
> user@host:~/yubihsm-ssh-tool$

**Comment by a-dma** [comment]
I just re-tested all the steps and it works on my end. I see you're using a different authentication key from the default one (as you should). How was this created? Could you provide the list of capabilities for that authentication key? You can get the list with

```yubihsm-shell -a get-object-info --authkey=2 --password=... -t authentication-key -i 2```

Also, _please_ format terminal dumps as code and not as quotes. It makes the text unreadable otherwise.

**Comment by mmahler** [comment]
Apologies for the format. This is what I get from that command: 

`
user@host:~$ yubihsm-shell -a get-object-info --authkey=2 --password=... -t authentication-key -i 2
Using default connector URL: http://127.0.0.1:12345
Session keepalive set up to run every 15 seconds
Created session 0
id: 0x0002, type: authentication-key, algorithm: aes128-yubico-authentication, label: "Master Operations Key", length: 40, domains: 1:2:3:4:5:6:7:8:9:10:11:12:13:14:15:16, sequence: 0, origin: imported, capabilities: change-authentication-key:create-otp-aead:decrypt-oaep:decrypt-otp:decrypt-pkcs:delete-asymmetric-key:delete-authentication-key:delete-hmac-key:delete-opaque:delete-otp-aead-key:delete-template:delete-wrap-key:derive-ecdh:export-wrapped:exportable-under-wrap:generate-asymmetric-key:generate-hmac-key:generate-otp-aead-key:generate-wrap-key:get-log-entries:get-opaque:get-option:get-pseudo-random:get-template:import-wrapped:put-asymmetric-key:put-authentication-key:put-mac-key:put-opaque:put-otp-aead-key:put-template:put-wrap-key:randomize-otp-aead:reset-device:rewrap-from-otp-aead-key:rewrap-to-otp-aead-key:set-option:sign-attestation-certificate:sign-ecdsa:sign-eddsa:sign-hmac:sign-pkcs:sign-pss:sign-ssh-certificate:unwrap-data:verify-hmac:wrap-data, delegated_capabilities: change-authentication-key:create-otp-aead:decrypt-oaep:decrypt-otp:decrypt-pkcs:delete-asymmetric-key:delete-authentication-key:delete-hmac-key:delete-opaque:delete-otp-aead-key:delete-template:delete-wrap-key:derive-ecdh:export-wrapped:exportable-under-wrap:generate-asymmetric-key:generate-hmac-key:generate-otp-aead-key:generate-wrap-key:get-log-entries:get-opaque:get-option:get-pseudo-random:get-template:import-wrapped:put-asymmetric-key:put-authentication-key:put-mac-key:put-opaque:put-otp-aead-key:put-template:put-wrap-key:randomize-otp-aead:reset-device:rewrap-from-otp-aead-key:rewrap-to-otp-aead-key:set-option:sign-attestation-certificate:sign-ecdsa:sign-eddsa:sign-hmac:sign-pkcs:sign-pss:sign-ssh-certificate:unwrap-data:verify-hmac:wrap-data
`

I had created the authentication key with the following: 
`
yubihsm-shell -a put-authentication-key -i 0x0002 -l "Master Operations Key" --new-password=... --capabilities=change-authentication-key:create-otp-aead:decrypt-oaep:decrypt-otp:decrypt-pkcs:delete-asymmetric-key:delete-authentication-key:delete-hmac-key:delete-opaque:delete-otp-aead-key:delete-template:delete-wrap-key:derive-ecdh:export-wrapped:exportable-under-wrap:generate-asymmetric-key:generate-hmac-key:generate-otp-aead-key:generate-wrap-key:get-log-entries:get-opaque:get-option:get-pseudo-random:get-template:import-wrapped:put-asymmetric-key:put-authentication-key:put-mac-key:put-opaque:put-otp-aead-key:put-template:put-wrap-key:randomize-otp-aead:reset-device:rewrap-from-otp-aead-key:rewrap-to-otp-aead-key:set-option:sign-attestation-certificate:sign-ecdsa:sign-eddsa:sign-hmac:sign-pkcs:sign-pss:sign-ssh-certificate:unwrap-data:verify-hmac:wrap-data --delegated=change-authentication-key:create-otp-aead:decrypt-oaep:decrypt-otp:decrypt-pkcs:delete-asymmetric-key:delete-authentication-key:delete-hmac-key:delete-opaque:delete-otp-aead-key:delete-template:delete-wrap-key:derive-ecdh:export-wrapped:exportable-under-wrap:generate-asymmetric-key:generate-hmac-key:generate-otp-aead-key:generate-wrap-key:get-log-entries:get-opaque:get-option:get-pseudo-random:get-template:import-wrapped:put-asymmetric-key:put-authentication-key:put-mac-key:put-opaque:put-otp-aead-key:put-template:put-wrap-key:randomize-otp-aead:reset-device:rewrap-from-otp-aead-key:rewrap-to-otp-aead-key:set-option:sign-attestation-certificate:sign-ecdsa:sign-eddsa:sign-hmac:sign-pkcs:sign-pss:sign-ssh-certificate:unwrap-data:verify-hmac:wrap-data
`

**Comment by a-dma** [comment]
Alright, that looks correct to me. One more question, what version of device do you have? You can use `get-device-info` to get that.

Older versions had a problem in validating the various constraints.

**Comment by mmahler** [comment]
Version number is 2.0.0

**Comment by a-dma** [comment]
Ah, I believe that version had a problem. You may want to get in touch with Support to get that resolved.
